openapi: 3.1.0
info:
  version: 1.0.0
  title: Travellers APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This app is for sharing travel experiences
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Operations with travelers (users)
  - name: Stories
    description: Operations with stories
  - name: Categories
    description: Operations with categories
servers:
  - url: http://localhost:8080/api
paths:
  # ендпоінти авторизації
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  # ендпоінти по роботі з користувачами
  # /users:
    # get:
    #   $ref:
  # ендпоінти по роботі з користувачами за ID
  # /users/{id}:
    # get:
    #   $ref:
  # ендпоінти по роботі з категоріями
  /categories:
    get:
      $ref: ../swagger/paths/categories/get.yaml
  # ендпоінти по роботі з історіями
  /stories:
    get:
      $ref: ../swagger/paths/stories/get.yaml
  # ендпоінти по роботі з історіями за ID
  # /stories/{id}:
    # post:
    #   $ref:
    # patch:
    #   $ref:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
